import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./hooks/themeProvider";
import { TemperatureProvider } from "./hooks/temperatureProvider";
import { WeatherProvider } from "./hooks/weatherProvider";
import { LoaderProvider } from "./hooks/loaderProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoaderProvider>
          <ThemeProvider>
            <TemperatureProvider>
              <WeatherProvider>{children}</WeatherProvider>
            </TemperatureProvider>
          </ThemeProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
